version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
    groups:
      javascript-development:
        dependency-type: development
      javascript-runtime:
        dependency-type: production

  - package-ecosystem: pip
    directory: /apps/agent
    schedule:
      interval: weekly
      day: monday

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
      day: monday

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
