services:
  postgres-archeon:
    container_name: postgres-archeon
    image: ankane/pgvector:latest
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-archeon-storage:/var/lib/postgresql/data/
    networks:
      - archeon-net
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "postgres"]
      interval: 10s
      timeout: 3s
      retries: 3

  redis-archeon:
    container_name: redis-archeon
    image: redis:alpine
    restart: unless-stopped
    ports:
      - "6378:6379"
    volumes:
      - redis-archeon-storage:/data
    command: redis-server --appendonly yes --requirepass RedisPassword123
    networks:
      - archeon-net
    healthcheck:
      test:
        [
          "CMD",
          "redis-cli",
          "--no-auth-warning",
          "-a",
          "RedisPassword123",
          "ping",
        ]
      interval: 10s
      timeout: 5s
      retries: 3

  gate:
    container_name: archeon-gate
    image: node:22-alpine
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - ../:/app
      - gate-node-modules:/app/node_modules
      - gate-app-node-modules:/app/apps/gate/node_modules
      - yarn-cache:/root/.yarn
    env_file:
      - ../apps/gate/.env
    command: >
      sh -c "
        yarn install &&
        yarn workspace @archeon-org/types build &&
        yarn workspace @archeon-org/database build &&
        yarn workspace @archeon-org/module build &&
        yarn workspace gate migration:run &&
        yarn workspace gate start:dev
      "
    depends_on:
      postgres-archeon:
        condition: service_healthy
      redis-archeon:
        condition: service_healthy
    networks:
      - archeon-net
    restart: unless-stopped

    tty: true

  scribe-api:
    container_name: archeon-scribe-api
    build:
      context: ../apps/scribe
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ../apps/scribe/src:/app/src:ro
    env_file:
      - ../apps/scribe/.env
    depends_on:
      postgres-archeon:
        condition: service_healthy
      redis-archeon:
        condition: service_healthy
    networks:
      - archeon-net
    restart: unless-stopped

  scribe-worker:
    container_name: archeon-scribe-worker
    build:
      context: ../apps/scribe
      dockerfile: Dockerfile.dev
    volumes:
      - ../apps/scribe/src:/app/src:ro
    env_file:
      - ../apps/scribe/.env
    command: >
      watchfiles 
      --filter python 
      'celery -A core.celery_app worker --loglevel=DEBUG --concurrency=2'
      /app/src
    depends_on:
      postgres-archeon:
        condition: service_healthy
      redis-archeon:
        condition: service_healthy
    networks:
      - archeon-net
    restart: unless-stopped


networks:
  archeon-net:
    driver: bridge

volumes:
  postgres-archeon-storage:
  redis-archeon-storage:
  gate-node-modules:
  gate-app-node-modules:
  yarn-cache:
