module.exports = {
  rootDir: ".",
  testEnvironment: "node",
  testMatch: ["<rootDir>/test/**/*.spec.ts", "<rootDir>/test/**/*.spec.tsx"],
  moduleFileExtensions: ["ts", "tsx", "js", "jsx", "json"],
  transform: {
    "^.+\\.(ts|tsx|js|jsx)$": "babel-jest",
  },
  moduleNameMapper: {
    "^@/(.*)$": "<rootDir>/src/$1",
    "^react-native$": "<rootDir>/test/mocks/react-native.ts",
    "^expo/virtual/env$": "<rootDir>/test/mocks/expo-virtual-env.js",
    "^expo-router$": "<rootDir>/test/mocks/expo-router.tsx",
    "^react-native-safe-area-context$":
      "<rootDir>/test/mocks/react-native-safe-area-context.tsx",
    "^react-native-gesture-handler$":
      "<rootDir>/test/mocks/react-native-gesture-handler.tsx",
    "^nativewind$": "<rootDir>/test/mocks/nativewind.ts",
    "^expo-constants$": "<rootDir>/test/mocks/expo-constants.ts",
    "^expo-splash-screen$": "<rootDir>/test/mocks/expo-splash-screen.ts",
    "^@expo/vector-icons$": "<rootDir>/test/mocks/expo-vector-icons.tsx",
    "^react-native/Libraries/Animated/NativeAnimatedHelper$":
      "<rootDir>/test/mocks/empty-object.js",
    "\\.(png|jpg|jpeg|gif|webp|svg)$": "<rootDir>/test/mocks/file-mock.js",
    "\\.css$": "<rootDir>/test/mocks/style-mock.js",
  },
  collectCoverageFrom: [
    "src/services/**/*.{ts,tsx}",
    "src/utils/**/*.{ts,tsx}",
    "src/constants/**/*.{ts,tsx}",
    "src/context/AuthContext.tsx",
    "src/context/ToastContext.tsx",
    "src/context/BiometricContext.tsx",
    "src/hooks/useDebounce.ts",
    "src/hooks/useOnboarding.ts",
    "src/hooks/useOtpLogin.ts",
    "src/hooks/useQuestion.ts",
    "src/hooks/useSemanticSearch.ts",
    "src/hooks/useDocumentUpload.ts",
    "src/hooks/useUser.ts",
    "src/components/Button.tsx",
    "src/components/Input.tsx",
    "src/components/GoogleButton.tsx",
    "src/components/NotificationBell.tsx",
    "src/components/document/DocumentStatusBadge.tsx",
    "src/components/document/DocumentsEmptyState.tsx",
    "src/components/common/ViewModeToggle.tsx",
    "src/components/common/StorageProgress.tsx",
    "src/components/common/Skeleton.tsx",
    "src/components/scan/ScanEmptyState.tsx",
    "src/components/icons/GoogleIcon.tsx",
    "src/app/index.tsx",
    "src/app/terms.tsx",
    "src/app/privacy.tsx",
    "src/app/notifications.tsx",
    "src/app/(auth)/welcome.tsx",
    "src/app/(auth)/login.tsx",
    "src/app/(auth)/otp.tsx",
    "src/app/(auth)/_layout.tsx",
    "src/app/_layout.tsx",
    "src/app/(app)/_layout.tsx",
    "!src/services/index.ts",
  ],
  setupFilesAfterEnv: ["<rootDir>/test/setup.ts"],
  clearMocks: true,
};
